### PR TITLE
Changes for SQL Server support

### PR DESCRIPTION
**Pull request by tsegismont**
Please review each commit separetely.

### CODE REVIEW

**Comment by DavideD** [comment]
Thanks, I will try this soon

**Comment by tsegismont** [comment]
No worries!

**Comment by DavideD** [comment]
THanks @tsegismont !

I've rebased this on a new branch that I will push on `hibernate/hibernate-reactive` or merge if ready 
(I still haven't checked all the the changes).

**Comment by tsegismont** [comment]
@DavideD great! Which is the new branch?

**Comment by DavideD** [comment]
This is the branch: https://github.com/hibernate/hibernate-reactive/tree/wip/mssql

**Pull request closed without merging**
